# .coveralls.yml example configuration

service_name: travis-ci # travis-ci or travis-pro

# for php-coveralls
src_dir: ../../phpBB3
coverage_clover: ../../phpBB3/build/logs/clover.xml
json_path: ../../phpBB3/build/logs/coveralls-upload.json