services:
    un1matr1x.ogame.controller:
        class: un1matr1x\ogame\controller\main
        arguments:
            - @config
            - @controller.helper
            - @template
            - @user
    un1matr1x.ogame.listener:
        class: un1matr1x\ogame\event\main_listener
        arguments:
            - %core.php_ext%
            - @service_container
            - @dbal.conn
            - @config
            - @controller.helper
            - @auth
            - @template
            - @user
            - @path_helper
            - @ext.manager
        tags:
            - { name: event.listener }
