services:
    un1matr1x.ogame.listener:
        class: un1matr1x\ogame\event\main_listener
        arguments:
            - @config
            - @un1matr1x.ogame.cr4me_link
            - @un1matr1x.ogame.profile_cards
            - @template
            - @user
            - @dbal.conn
            - @controller.helper
        tags:
            - { name: event.listener }
    un1matr1x.ogame.cr4me_link:
        class: un1matr1x\ogame\core\cr4me_link
        arguments:
            - @config
    un1matr1x.ogame.profile_cards:
        class: un1matr1x\ogame\core\profile_cards
        arguments:
            - @dbal.conn
            - @user
            - @service_container
